//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Social
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circle
    {
        public Circle()
        {
            this.Contacts = new HashSet<Contact>();
            this.Broadcasts = new HashSet<Broadcast>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Broadcast> Broadcasts { get; set; }
    }
}
