//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Social
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Inbox = new HashSet<Exchange>();
            this.Outbox = new HashSet<Exchange>();
            this.Feeds = new HashSet<Broadcast>();
        }
    
        public int Id { get; set; }
    
        public virtual Identity Identity { get; set; }
        public virtual Circle Circle { get; set; }
        public virtual ICollection<Exchange> Inbox { get; set; }
        public virtual ICollection<Exchange> Outbox { get; set; }
        public virtual ICollection<Broadcast> Feeds { get; set; }
    }
}
