//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Social
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.Exchanges = new HashSet<Exchange>();
            this.Broadcasts = new HashSet<Broadcast>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
    
        public virtual Identity Author { get; set; }
        public virtual ICollection<Exchange> Exchanges { get; set; }
        public virtual ICollection<Broadcast> Broadcasts { get; set; }
    }
}
