//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Reflection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Dependencies = new HashSet<Area>();
            this.Domains = new HashSet<Domain>();
        }
    
        public int Id { get; set; }
    
        public virtual Term Term { get; set; }
        public virtual ICollection<Area> Dependencies { get; set; }
        public virtual Area Principal { get; set; }
        public virtual ICollection<Domain> Domains { get; set; }
    }
}
