//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Reflection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domain
    {
        public Domain()
        {
            this.Members = new HashSet<Member>();
        }
    
        public int Id { get; set; }
    
        public virtual Term Term { get; set; }
        public virtual Area Area { get; set; }
        public virtual ICollection<Member> Members { get; set; }
    }
}
