//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.Reflection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReflectionModelContainer : DbContext
    {
        public ReflectionModelContainer()
            : base("name=ReflectionModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Term> Terms { get; set; }
        public DbSet<Domain> Domains { get; set; }
        public DbSet<Area> Areas { get; set; }
        public DbSet<Member> Members { get; set; }
    }
}
